# Generated by Django 5.2.3 on 2025-06-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='algo', max_length=100),
            preserve_default=False,
        ),
    ]
