# Generated by Django 5.2.3 on 2025-07-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='type',
            new_name='movement_type',
        ),
    ]
