# Generated by Django 5.2.3 on 2025-07-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0002_rename_type_movement_movement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='movement_type',
            new_name='transaction_type',
        ),
    ]
